### ISSUE TITLE
Back-end development of the cuisine

### ISSUE THREAD

**Issue by Ephantuz** [ShaifArfan/shaif-s-cuisine#18]
Hi, Would you like a back-end development of this cuisine to make it a complete application using node and MongoDB?  I just wanted to contribute to this amazing project. I believe we can come up with an amazing application for this cuisine store just for you!

**Comment by ShaifArfan** [comment]
Hey, Thanks for your concern. This repo is for educational tutorial. So there is no need for any backend right now. Thanks.
